In [ ]:
import numpy as np
def knight_tour(n):
  board=[[-1 for i in range(n)]for j in range(n)]
  knight_tour_helper(n=n,board=board,x=4,y=0,counter=0)
  print(np.array(board))
def knight_tour_helper(n,board,x,y,counter):
  if counter==n*n:
    return True
  if(x<0)or (x>=n) or (y<0)or (y>=n)or board[y][x]!= -1:
    return False
  board[y][x]=counter
  for x_move,y_move in zip([-2,-2,-1,-1,1,1,2,2],[-1,1,-2,2,-2,2,-1,1]):
    if knight_tour_helper(n,board,x+x_move,y+y_move,counter+1):
      return True
  board[y][x]=-1
  return False

In [ ]:
knight_tour(6)

[[ 2  7 22 19  0 31]
 [ 9 20  1 32 23 18]
 [ 6  3  8 21 30 33]
 [13 10  5 26 17 24]
 [ 4 27 12 15 34 29]
 [11 14 35 28 25 16]]
