In [1]:
import numpy as np
N  = int(input("enter the square  matrix number"))
if N%2==0:
  print("magic square wont work on even matrix size.")
  print("enter odd number ")
magic_square = np.zeros((N,N), dtype=int)
n = 1
i= 0
j = N//2

while n <= N**2:
    magic_square[i, j] = n
    n+=1
    x = (i-1) % N
    y = (j+1)% N
    if magic_square[x, y]:
        i +=1
    else:
        i, j = x, y
print("Solved Magic Square is:")
print(magic_square)

enter the square  matrix number3
Solved Magic Square is:
[[8 1 6]
 [3 5 7]
 [4 9 2]]
